copyright: Copyright &copy; 2016 - 2025 MapGallery B.V.
site_name: MapGallery GeoStyler kookboek
site_url: https://docs.mapgallery.eu/
repo_url: https://github.com/mapgallery/documentation
edit_uri: edit/main/docs/
extra:
  analytics:
    provider: plausible
    domain: docs.mapgallery.eu
  homepage: https://mapgallery.eu
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:<info@mapgallery.eu>
    - icon: fontawesome/brands/github
      link: https://github.com/mapgallery
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/mapgallery
  version:
    provider: mike
extra_css:
  - assets/css/extra.css
markdown_extensions:
  - abbr
  - admonition
  - meta
  - pymdownx.keys
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - tables
  - toc
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  
nav:
  - Kookboek:
      - index.md
      -  gallerij/index.md
      - punten/index.md
      - lijnen/index.md
      - vlakken/index.md

plugins:
  - macros:
      include_dir: includes
  - material-plausible
  - search
  - social
  - tags
  - glightbox:
      zoomable: true

theme:
  name: material
  favicon: assets/favicon.png
  features:
    - content.action.edit
    - content.action.view
#    - navigation.expand
    - navigation.path
    - navigation.footer
#    - navigation.indexes
    - navigation.sections
#    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
#    - toc.follow
#    - toc.integrate
  language: nl
  logo: assets/logo.png
validation:
  links:
    absolute_links: relative_to_docs
watch:
  - includes